-- 1
SELECT CITY , STATE from STATION
--2
--3
SELECT DISTINCT CITY FROM STATION WHERE ID % 2 = 0
--4
SELECT COUNT(CITY) - COUNT(DISTINCT CITY) FROM STATION
--5
(SELECT CITY , LENGTH(CITY) FROM STATION ORDER BY LENGTH(CITY) ASC , CITY ASC LIMIT 1)
UNION
(SELECT CITY , LENGTH(CITY) FROM STATION ORDER BY LENGTH(CITY) DESC , CITY DESC LIMIT 1)
--6
SELECT DISTINCT CITY FROM STATION WHERE
LOWER(CITY) LIKE 'a%' OR
LOWER(CITY) LIKE 'e%' OR
LOWER(CITY) LIKE 'i%' OR
LOWER(CITY) LIKE 'o%' OR
LOWER(CITY) LIKE 'u%';
--7
SELECT DISTINCT CITY FROM STATION WHERE
LOWER(CITY) LIKE '%a' OR
LOWER(CITY) LIKE '%e' OR
LOWER(CITY) LIKE '%i' OR
LOWER(CITY) LIKE '%o' OR
LOWER(CITY) LIKE '%u';
--8
SELECT DISTINCT CITY FROM STATION WHERE
(LOWER(CITY) LIKE '%a' OR
LOWER(CITY) LIKE '%e' OR
LOWER(CITY) LIKE '%i' OR
LOWER(CITY) LIKE '%o' OR
LOWER(CITY) LIKE '%u') AND
(LOWER(CITY) LIKE 'a%' OR
LOWER(CITY) LIKE 'e%' OR
LOWER(CITY) LIKE 'i%' OR
LOWER(CITY) LIKE 'o%' OR
LOWER(CITY) LIKE 'u%');
--9
SELECT DISTINCT CITY FROM STATION WHERE
(LOWER(CITY) NOT LIKE 'a%' AND
LOWER(CITY) NOT LIKE 'e%' AND
LOWER(CITY) NOT LIKE 'i%' AND
LOWER(CITY) NOT LIKE 'o%' AND
LOWER(CITY) NOT LIKE 'u%')
--10
SELECT DISTINCT CITY FROM STATION WHERE
(LOWER(CITY) NOT LIKE '%a' AND
LOWER(CITY) NOT LIKE '%e' AND
LOWER(CITY) NOT LIKE '%i' AND
LOWER(CITY) NOT LIKE '%o' AND
LOWER(CITY) NOT LIKE '%u')
--11
SELECT DISTINCT CITY FROM STATION
WHERE
Lower(Left(City,1)) NOT IN ('a', 'e', 'i', 'o', 'u')
OR
Lower(RIGHT(City,1)) NOT IN ('a', 'e', 'i', 'o', 'u');
--12
SELECT DISTINCT CITY FROM STATION
WHERE
Lower(Left(City,1)) NOT IN ('a', 'e', 'i', 'o', 'u')
AND
Lower(RIGHT(City,1)) NOT IN ('a', 'e', 'i', 'o', 'u');
--20
SELECT ROUND(AVG(Lat_n),4)
from(
    SELECT Lat_n,
    Row_NUMBER() OVER(ORDER BY Lat_n) as rn,
    count(*) OVER() as total
    from Station) as sub
WHERE rn IN (FLOOR((total + 1) / 2), CEIL((total + 1) / 2));

